language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn test
notifications:
    slack: extrememoderation:VJtsYtiLpOpJy9Krlq8rZpxv
# TODO: deploy to heroku (or where ever)